---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2019/5/14 15:56
---
lua_obj = nil
lua_obj2 = nil

function InitValue(go)
    print('Lua Call function InitValue params: ' .. tostring(go.name))

    lua_obj = go
    print("lua_obj = " .. tostring(lua_obj))
end

function TestValue()
    print("lua_obj == nil : " .. tostring(lua_obj == nil))
    print("lua_obj == null : " .. tostring(lua_obj == null))
    print("lua_obj:Equal(nil) : " .. tostring(lua_obj:Equals(nil)))
    print("lua_obj:Equal(null) : " .. tostring(lua_obj:Equals(null)))
end

function InitValue2()
    print("InitValue2")
    lua_obj2 = UnityEngine.GameObject.New("Lua_obj2")
    print("lua_obj2 = " .. tostring(lua_obj2))
end

function TestValue2()
    print("TestValue2")
    UnityEngine.GameObject.DestroyImmediate(lua_obj2)
    print("lua_obj2 == nil : " .. tostring(lua_obj2 == nil))
    print("lua_obj2 == null : " .. tostring(lua_obj2 == null))
    print("lua_obj2:Equal(nil) : " .. tostring(lua_obj2:Equals(nil)))
    print("lua_obj2:Equal(null) : " .. tostring(lua_obj2:Equals(null)))
end

function TestValue3()
    print("TestValue3")
    local lua_obj3 = UnityEngine.GameObject.New("lua_obj3")
    UnityEngine.GameObject.DestroyImmediate(lua_obj3)
    print("lua_obj3 == nil : " .. tostring(lua_obj3 == nil))
    print("lua_obj3 == null : " .. tostring(null == lua_obj3))
    print("lua_obj3:Equal(nil) : " .. tostring(lua_obj3:Equals(nil)))
    print("lua_obj3:Equal(null) : " .. tostring(lua_obj3:Equals(null)))
end

function TestValue4()
    local tt = {0, "data", 2, 3, 4, {"child01", 1}}
    return tt
end

function TestTableToLua(tab)
    print("TestTableToLua")
    print("----------tab.name = " .. tab.name)
    print("----------tab.id = " .. tostring(tab.id))
    if tab.data then
        for i = 1, #(tab.data) do
            for j = 1, #(tab.data[i]) do
                print(string.format("i = %s, j = %s, data = %s", tostring(i), tostring(j), tostring(tab.data[i][j])))
            end
        end
    else
        print("tab.data = nil")
    end
end

-- C#不能传递函数到Lua中
function TestCSharpDelegate(ok_cb)
    print("TestCSharpDelegate")
    if ok_cb then
        print("TestCSharpDelegate 1")
        ok_cb()
    end
end

function TestVector3Operator(trans)
    print("TestVector3Operator")
    -- Lua不支持Vector3的这种操作符
    -- local tmpVec3 = 1000 * trans.localPosition
    local tmpVec3 = Vector3.New(1000 * trans.localPosition.x, 1000 * trans.localPosition.y, 1000 * trans.localPosition.z)
    print(string.format("1 tmpVec3.x = %d, y = %d, z = %d", tmpVec3.x, tmpVec3.y, tmpVec3.z))
    tmpVec3 = tmpVec3 + trans.localPosition
    print(string.format("2 tmpVec3.x = %d, y = %d, z = %d", tmpVec3.x, tmpVec3.y, tmpVec3.z))

    local reverse = false
    print(string.format("1 reverse = %s; not reverse = %s", tostring(reverse), tostring(not reverse)))
    reverse = nil
    print(string.format("2 reverse = %s; not reverse = %s", tostring(reverse), tostring(not reverse)))

    local vec1 = Vector3.New(100, 100, 100)
    local vec2 = Vector3.New(50, 50, 50)
    local vec3 = vec1 - vec2
    print()

end

function TestCSharpDefaultParams()
    print("TestCSharpDefaultParams")
    CSharpLuaTest.CommonTransfer.SetPlayerInfo(1, 2, "zzf")
end