---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2019/6/26 15:54
---

function Util.PrintVector3(vec3)
    print(string.format("x = %d, y = %d, z = %d", vec3.x, vec3.y, vec3.z))
end